services:
  
  backend:
    build:
      context: ./app/
    ports:
      - "5000:5000"
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: freemarket
    depends_on:
      - mysql

  frontend:
    build:
      context: ../fmfrontend/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - mysql
      - backend

  mysql:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freemarket
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: