services:
  
  backend:
    build:
      context: ./app/
    ports:
      - "5000:5000"
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: freemarket
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freemarket
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker_db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql 
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: